## Manipulation

In [1]:
import pandas as pd

df = pd.read_csv("Olist.csv")

# cette transformation est juste pour avoir int8 au lieu de int64
int_col = ["payment_sequential","payment_installments","order_item_id","review_score","review_answer_timestamp","product_photos_qty","order_delivered_customer_date"]
object_col = ["order_item_id","customer_zip_code_prefix"]

for col in int_col:

    df[col] = pd.to_numeric(df[col], errors='coerce',downcast='integer')

for col in object_col:
    df[col] = df[col].astype(str)
    
df.head()

,order_id,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value,order_item_id,product_id,...,review_answer_timestamp,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_photos_qty
0,e481f51cbdc54678b7cc49136f2d6af7,455,447,439,1,credit_card,1,18.12,1,87285b34884572647811a353c7ac498a,...,445,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,Home,4
1,e481f51cbdc54678b7cc49136f2d6af7,455,447,439,3,voucher,1,2.00,1,87285b34884572647811a353c7ac498a,...,445,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,Home,4
2,e481f51cbdc54678b7cc49136f2d6af7,455,447,439,2,voucher,1,18.59,1,87285b34884572647811a353c7ac498a,...,445,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350,maua,SP,Home,4
3,53cdb2fc8bc7dce0b6741e2150273451,160,146,140,1,boleto,1,141.46,1,595fac2a385ac33a80bd5114aec74eb8,...,145,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,31570,belo horizonte,SP,Health_Beauty,1
4,47770eb9100c2d0c44946d9cf07ec65d,145,136,118,1,credit_card,3,179.12,1,aa4383b373c6aca5d8797843e5594415,...,131,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,14840,guariba,SP,Automotive,1

In [2]:
df[df["payment_sequential"].isna()]

Empty DataFrame
Columns: [order_id, order_purchase_timestamp, order_delivered_customer_date, order_estimated_delivery_date, payment_sequential, payment_type, payment_installments, payment_value, order_item_id, product_id, seller_id, price, freight_value, review_id, review_score, review_answer_timestamp, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state, seller_zip_code_prefix, seller_city, seller_state, product_category_name, product_photos_qty]
Index: []

[0 rows x 25 columns]

## Group by & AggrÃ©gation

In [3]:
# SÃ©paration des colonnes par mÃ©thode d'aggrÃ©gation

mode_col = ['payment_sequential','payment_type','payment_installments','product_id','seller_state',
            'seller_id','customer_zip_code_prefix','customer_city','product_category_name','customer_state','seller_zip_code_prefix','seller_city','product_photos_qty']
mean_col = ['payment_value','price','freight_value','review_score']
last_col = ['order_purchase_timestamp','order_delivered_customer_date','order_estimated_delivery_date','review_answer_timestamp']
count_col = ['order_id']

In [4]:
from statistics import mode

# crÃ©ation d'une fonction qui fait le mode

def compute_mode(x):
    try:
        return mode(x)
    except:
        return None

In [5]:
# crÃ©ation d'un dictionnaire qui lie la colonne Ã  la mÃ©thode choisit dans la fonction d'aggrÃ©gation

agg_dict = {}

for col in mode_col:
    agg_dict[col] = lambda x: compute_mode(x)

for col in mean_col:
    agg_dict[col] = 'mean'

for col in last_col:
    agg_dict[col] = 'min'

for col in count_col:
    agg_dict[col] = 'count'

In [6]:
# application de l'aggrÃ©gation

df_agg = df.groupby('customer_unique_id').agg(agg_dict)

df_agg

,payment_sequential,payment_type,payment_installments,product_id,seller_state,seller_id,customer_zip_code_prefix,customer_city,product_category_name,customer_state,...,product_photos_qty,payment_value,price,freight_value,review_score,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,review_answer_timestamp,order_id
customer_unique_id,,,,,,,,,,,,,,,,,,,,,
0000366f3b9a7992bf8c76cfdf3221e2,1,credit_card,8,372645c7439f9661fbbacfd129aa92ec,SP,da8622b14eb17ae2831f4ac5b9dab84a,7787,cajamar,Home,SP,...,1,141.90,129.90,12.00,5.0,235,229,224,224,1
0000b849f77a49e4a4ce2b2a4ca5be3f,1,credit_card,1,5099f7000472b634fea8304448d20825,SP,138dbe45fc62f1e244378131a6801526,6053,osasco,Health_Beauty,SP,...,1,27.19,18.90,8.29,4.0,238,235,230,234,1
0000f46a3911fa3c0805444483337064,1,credit_card,8,64b488de448a5324c4134ea39c28a34b,SP,3d871de0142ce09b7081e2b9d1733cb1,88115,sao jose,Office_Supplies,SC,...,3,86.22,69.00,17.22,3.0,661,635,633,633,1
0000f6ccb0745a6a4b88665a16c9f078,1,credit_card,4,2345a354a6f2033609bbf62bf5be9ef6,SP,ef506c96320abeedfb894c34db06f478,66812,belem,Technology,PA,...,5,43.62,25.99,17.63,4.0,445,425,413,423,1
0004aac84e0df4da2b147fca70cf8255,1,credit_card,6,c72e18b3fe2739b8d24ebf3102450f37,SP,70a12e78e608ac31179aea7f8422044b,18040,sorocaba,Technology,SP,...,3,196.89,180.00,16.89,5.0,412,399,391,394,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fffcf5a5ff07b0908bd4e2dbc735a684,1,credit_card,10,c100e5fef1abb5e1c5054d1dac2d83ac,SP,17f51e7198701186712e53a39c564617,55250,sanharo,Health_Beauty,PE,...,1,2067.42,785.00,248.71,5.0,571,543,516,538,2
fffea47cd6d3cc0a88bd621562a9d061,1,credit_card,1,251876e7ba013b87b7262fb2524e2d60,SP,7aa4334be125fcdd2ba64b3180029f14,44054,feira de santana,Baby,BA,...,2,84.58,64.89,19.69,4.0,386,356,353,350,1
ffff371b4d645b6ecea244b27531430a,1,credit_card,1,13ad6994bda56edfa0a269e3d9a9acb3,MG,54aa8463e87776b5612f4bdc4bd5d4de,78552,sinop,Automotive,MT,...,5,112.46,89.90,22.56,5.0,692,677,647,674,1
ffff5962728ec6157033ef9805bacc48,1,credit_card,5,461f43be3bdf8844e65b62d9ac2c7a5a,SP,7d13fca15225358621be4086e1eb0964,29460,bom jesus do norte,Fashion_Accessories,ES,...,3,133.69,115.00,18.69,5.0,243,231,217,228,1
ffffd2657e2aad2907e67c3e9daecbeb,1,credit_card,4,bbaef2eadf31fe3ea6702077398be06c,SP,cc419e0650a3c5ba77189a1882b7556a,83608,campo largo,Health_Beauty,PR,...,2,71.56,56.99,14.57,5.0,608,600,584,597,1

## R.F.M score

### RÃ©cence

In [7]:
import numpy as np

# DÃ©finition les point Ã  accorder
pts = [15,10,6,3,0]

# DÃ©finition des conditions
conditions = [
    df_agg['order_purchase_timestamp'] < 93,
    (df_agg['order_purchase_timestamp'] >= 93) & (df_agg['order_purchase_timestamp'] < 185),
    (df_agg['order_purchase_timestamp'] >= 185) & (df_agg['order_purchase_timestamp'] < 276),
    (df_agg['order_purchase_timestamp'] >= 276) & (df_agg['order_purchase_timestamp'] < 366),
    df_agg['order_purchase_timestamp'] >= 366
]

# Application et crÃ©ation de la nouvelle colonne 'R' 
df_agg["R"] = np.select(conditions,pts)

### FrÃ©quence

In [8]:
# selection des donnÃ©es des 12 derniers mois
df_last_year = df[df["order_purchase_timestamp"]<366]

df_last_year

,order_id,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,payment_sequential,payment_type,payment_installments,payment_value,order_item_id,product_id,...,review_answer_timestamp,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,product_category_name,product_photos_qty
3,53cdb2fc8bc7dce0b6741e2150273451,160,146,140,1,boleto,1,141.46,1,595fac2a385ac33a80bd5114aec74eb8,...,145,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,31570,belo horizonte,SP,Health_Beauty,1
4,47770eb9100c2d0c44946d9cf07ec65d,145,136,118,1,credit_card,3,179.12,1,aa4383b373c6aca5d8797843e5594415,...,131,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,14840,guariba,SP,Automotive,1
6,ad21c59c0840e6cb83a9ceb5573f8159,321,318,308,1,credit_card,1,28.62,1,65266b2da20d04dbe00c5c2d3bb7859e,...,316,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,8752,mogi das cruzes,SP,Office_Supplies,4
15,82566a660a982b15fb86e904c8d32918,207,195,166,1,boleto,1,50.13,1,72a97c271b2e429974398f46b93ae530,...,194,e97109680b052ee858d93a539597bba7,35400,ouro preto,MG,14095,ribeirao preto,SP,Health_Beauty,1
16,5ff96c15d0b717ac6ad1f3d77225a350,159,154,145,1,credit_card,3,32.70,1,10adb53d8faa890ca7c2f0cbcb68d777,...,151,e2dfa3127fedbbca9707b36304996dab,4812,sao paulo,SP,14940,ibitinga,SP,Home,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113216,c81f74e50f0496fa39716cc77cacd460,302,293,280,1,credit_card,2,70.83,1,cb92637d91f8267856d2143b6fc7bd9e,...,290,324a22205906aa2612a33e63c00ca8bb,31130,belo horizonte,MG,74323,goiania,GO,Sports_Leisure,4
113227,63943bddc261676b46f01ca7ac2f7bd8,328,306,304,1,credit_card,3,195.00,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,...,304,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP,17602,tupa,SP,Baby,4
113229,11c177c8e97725db2631073c19f07b62,357,340,319,1,credit_card,4,441.16,1,d1c427060a0f73f6b889a5c7c61f2ac4,...,338,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,37175,ilicinea,MG,Technology,1
113230,11c177c8e97725db2631073c19f07b62,357,340,319,1,credit_card,4,441.16,2,d1c427060a0f73f6b889a5c7c61f2ac4,...,338,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ,37175,ilicinea,MG,Technology,1
113231,66dea50a8b16d9b4dee7af250b4be1a5,298,290,272,1,debit_card,1,86.86,1,006619bbed68b000c8ba3f8725d5409e,...,289,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR,14407,franca,SP,Health_Beauty,1

In [9]:
# aggrÃ©gation par nombre de fois de commande par client

df_year_agg = df_last_year.groupby('customer_unique_id')['order_id'].nunique().reset_index(name='unique_orders_count')

df_year_agg

                     customer_unique_id  unique_orders_count
0      0000366f3b9a7992bf8c76cfdf3221e2                    1
1      0000b849f77a49e4a4ce2b2a4ca5be3f                    1
2      0004bd2a26a76fe21f786e4fbd80607f                    1
3      00050ab1314c0e55a6ca13cf7181fecf                    1
4      00053a61a98854899e70ed204dd4bafe                    1
...                                 ...                  ...
50806  fff2ae16b99c6f3c785f0e052f2a9cfb                    1
50807  fff3e1d7bc75f11dc7670619b2e61840                    1
50808  fff5eb4918b2bf4b2da476788d42051c                    1
50809  fff96bc586f78b1f070da28c4977e810                    1
50810  ffff5962728ec6157033ef9805bacc48                    1

[50811 rows x 2 columns]

In [10]:
# application du bonnus de 3 points pour chaque commande 

df_year_agg["unique_orders_count"] = df_year_agg["unique_orders_count"].apply(lambda x : x*3)

# changement du nom de la colonne en 'F' pour frÃ©quence

df_year_agg = df_year_agg.rename(columns={'unique_orders_count':'F'})

df_year_agg

                     customer_unique_id  F
0      0000366f3b9a7992bf8c76cfdf3221e2  3
1      0000b849f77a49e4a4ce2b2a4ca5be3f  3
2      0004bd2a26a76fe21f786e4fbd80607f  3
3      00050ab1314c0e55a6ca13cf7181fecf  3
4      00053a61a98854899e70ed204dd4bafe  3
...                                 ... ..
50806  fff2ae16b99c6f3c785f0e052f2a9cfb  3
50807  fff3e1d7bc75f11dc7670619b2e61840  3
50808  fff5eb4918b2bf4b2da476788d42051c  3
50809  fff96bc586f78b1f070da28c4977e810  3
50810  ffff5962728ec6157033ef9805bacc48  3

[50811 rows x 2 columns]

In [11]:
# merger le dataframe gÃ©nÃ©ral avec le rÃ©sultant en left, en remplanÃ§ant les nan par 0

df_agg = df_agg.merge(df_year_agg,how='left',on='customer_unique_id').fillna(0)

# petite transformation en int8

df_agg["F"] = pd.to_numeric(df_agg["F"], errors='coerce',downcast='integer')

df_agg

,customer_unique_id,payment_sequential,payment_type,payment_installments,product_id,seller_state,seller_id,customer_zip_code_prefix,customer_city,product_category_name,...,price,freight_value,review_score,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,review_answer_timestamp,order_id,R,F
0,0000366f3b9a7992bf8c76cfdf3221e2,1,credit_card,8,372645c7439f9661fbbacfd129aa92ec,SP,da8622b14eb17ae2831f4ac5b9dab84a,7787,cajamar,Home,...,129.90,12.00,5.0,235,229,224,224,1,6,3
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,credit_card,1,5099f7000472b634fea8304448d20825,SP,138dbe45fc62f1e244378131a6801526,6053,osasco,Health_Beauty,...,18.90,8.29,4.0,238,235,230,234,1,6,3
2,0000f46a3911fa3c0805444483337064,1,credit_card,8,64b488de448a5324c4134ea39c28a34b,SP,3d871de0142ce09b7081e2b9d1733cb1,88115,sao jose,Office_Supplies,...,69.00,17.22,3.0,661,635,633,633,1,0,0
3,0000f6ccb0745a6a4b88665a16c9f078,1,credit_card,4,2345a354a6f2033609bbf62bf5be9ef6,SP,ef506c96320abeedfb894c34db06f478,66812,belem,Technology,...,25.99,17.63,4.0,445,425,413,423,1,0,0
4,0004aac84e0df4da2b147fca70cf8255,1,credit_card,6,c72e18b3fe2739b8d24ebf3102450f37,SP,70a12e78e608ac31179aea7f8422044b,18040,sorocaba,Technology,...,180.00,16.89,5.0,412,399,391,394,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91493,fffcf5a5ff07b0908bd4e2dbc735a684,1,credit_card,10,c100e5fef1abb5e1c5054d1dac2d83ac,SP,17f51e7198701186712e53a39c564617,55250,sanharo,Health_Beauty,...,785.00,248.71,5.0,571,543,516,538,2,0,0
91494,fffea47cd6d3cc0a88bd621562a9d061,1,credit_card,1,251876e7ba013b87b7262fb2524e2d60,SP,7aa4334be125fcdd2ba64b3180029f14,44054,feira de santana,Baby,...,64.89,19.69,4.0,386,356,353,350,1,0,0
91495,ffff371b4d645b6ecea244b27531430a,1,credit_card,1,13ad6994bda56edfa0a269e3d9a9acb3,MG,54aa8463e87776b5612f4bdc4bd5d4de,78552,sinop,Automotive,...,89.90,22.56,5.0,692,677,647,674,1,0,0
91496,ffff5962728ec6157033ef9805bacc48,1,credit_card,5,461f43be3bdf8844e65b62d9ac2c7a5a,SP,7d13fca15225358621be4086e1eb0964,29460,bom jesus do norte,Fashion_Accessories,...,115.00,18.69,5.0,243,231,217,228,1,6,3
91497,ffffd2657e2aad2907e67c3e9daecbeb,1,credit_card,4,bbaef2eadf31fe3ea6702077398be06c,SP,cc419e0650a3c5ba77189a1882b7556a,83608,campo largo,Health_Beauty,...,56.99,14.57,5.0,608,600,584,597,1,0,0

### Montant

In [12]:
# groupement par client en aggrÃ©geant le payment en somme 

df_payment_agg = df.groupby('customer_unique_id')['payment_value'].sum().reset_index(name='M')

# transformer 2% du montant en pts, Ã§Ã  revient Ã  diviser par 50 le montant, et arrondir au nombre entier 
df_payment_agg['M'] = df_payment_agg['M'].apply(lambda x : int(round(x/50)))

# maximiser le nombre de points au 10 pts max
df_payment_agg['M'] = df_payment_agg['M'].apply(lambda x : 10 if x > 10 else x)

df_payment_agg

                     customer_unique_id   M
0      0000366f3b9a7992bf8c76cfdf3221e2   3
1      0000b849f77a49e4a4ce2b2a4ca5be3f   1
2      0000f46a3911fa3c0805444483337064   2
3      0000f6ccb0745a6a4b88665a16c9f078   1
4      0004aac84e0df4da2b147fca70cf8255   4
...                                 ...  ..
91493  fffcf5a5ff07b0908bd4e2dbc735a684  10
91494  fffea47cd6d3cc0a88bd621562a9d061   2
91495  ffff371b4d645b6ecea244b27531430a   2
91496  ffff5962728ec6157033ef9805bacc48   3
91497  ffffd2657e2aad2907e67c3e9daecbeb   1

[91498 rows x 2 columns]

In [13]:
# merger le dataframe gÃ©nÃ©ral avec le rÃ©sultant en left, en remplanÃ§ant les nan par 0

df_agg = df_agg.merge(df_payment_agg,how='left',on='customer_unique_id')

df_agg

,customer_unique_id,payment_sequential,payment_type,payment_installments,product_id,seller_state,seller_id,customer_zip_code_prefix,customer_city,product_category_name,...,freight_value,review_score,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,review_answer_timestamp,order_id,R,F,M
0,0000366f3b9a7992bf8c76cfdf3221e2,1,credit_card,8,372645c7439f9661fbbacfd129aa92ec,SP,da8622b14eb17ae2831f4ac5b9dab84a,7787,cajamar,Home,...,12.00,5.0,235,229,224,224,1,6,3,3
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,credit_card,1,5099f7000472b634fea8304448d20825,SP,138dbe45fc62f1e244378131a6801526,6053,osasco,Health_Beauty,...,8.29,4.0,238,235,230,234,1,6,3,1
2,0000f46a3911fa3c0805444483337064,1,credit_card,8,64b488de448a5324c4134ea39c28a34b,SP,3d871de0142ce09b7081e2b9d1733cb1,88115,sao jose,Office_Supplies,...,17.22,3.0,661,635,633,633,1,0,0,2
3,0000f6ccb0745a6a4b88665a16c9f078,1,credit_card,4,2345a354a6f2033609bbf62bf5be9ef6,SP,ef506c96320abeedfb894c34db06f478,66812,belem,Technology,...,17.63,4.0,445,425,413,423,1,0,0,1
4,0004aac84e0df4da2b147fca70cf8255,1,credit_card,6,c72e18b3fe2739b8d24ebf3102450f37,SP,70a12e78e608ac31179aea7f8422044b,18040,sorocaba,Technology,...,16.89,5.0,412,399,391,394,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91493,fffcf5a5ff07b0908bd4e2dbc735a684,1,credit_card,10,c100e5fef1abb5e1c5054d1dac2d83ac,SP,17f51e7198701186712e53a39c564617,55250,sanharo,Health_Beauty,...,248.71,5.0,571,543,516,538,2,0,0,10
91494,fffea47cd6d3cc0a88bd621562a9d061,1,credit_card,1,251876e7ba013b87b7262fb2524e2d60,SP,7aa4334be125fcdd2ba64b3180029f14,44054,feira de santana,Baby,...,19.69,4.0,386,356,353,350,1,0,0,2
91495,ffff371b4d645b6ecea244b27531430a,1,credit_card,1,13ad6994bda56edfa0a269e3d9a9acb3,MG,54aa8463e87776b5612f4bdc4bd5d4de,78552,sinop,Automotive,...,22.56,5.0,692,677,647,674,1,0,0,2
91496,ffff5962728ec6157033ef9805bacc48,1,credit_card,5,461f43be3bdf8844e65b62d9ac2c7a5a,SP,7d13fca15225358621be4086e1eb0964,29460,bom jesus do norte,Fashion_Accessories,...,18.69,5.0,243,231,217,228,1,6,3,3
91497,ffffd2657e2aad2907e67c3e9daecbeb,1,credit_card,4,bbaef2eadf31fe3ea6702077398be06c,SP,cc419e0650a3c5ba77189a1882b7556a,83608,campo largo,Health_Beauty,...,14.57,5.0,608,600,584,597,1,0,0,1

In [14]:
# create an RFM score from the 3 other columns

df_agg['RFM'] = df_agg['R'] + df_agg['F'] + df_agg['M']

# save the dataframe as csv file

df_agg.to_csv("Olist_cleaned.csv",index=False)

In [15]:
df_agg.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 91498 entries, 0 to 91497
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer_unique_id             91498 non-null  object
 1   payment_sequential             91498 non-null  int64
 2   payment_type                   91498 non-null  object
 3   payment_installments           91498 non-null  int64
 4   product_id                     91498 non-null  object
 5   seller_state                   91498 non-null  object
 6   seller_id                      91498 non-null  object
 7   customer_zip_code_prefix       91498 non-null  object
 8   customer_city                  91498 non-null  object
 9   product_category_name          91498 non-null  object
 10  customer_state                 91498 non-null  object
 11  seller_zip_code_prefix         91498 non-null  int64
 12  seller_city                    91498 non-null  object
 13  product_photos_qty             91498 non-null  int64
 14  payment_value                  91498 non-null  float64
 15  price                          91498 non-null  float64
 16  freight_value                  91498 non-null  float64
 17  review_score                   91498 non-null  float64
 18  order_purchase_timestamp       91498 non-null  int64
 19  order_delivered_customer_date  91498 non-null  int16
 20  order_estimated_delivery_date  91498 non-null  int64
 21  review_answer_timestamp        91498 non-null  int16
 22  order_id                       91498 non-null  int64
 23  R                              91498 non-null  int64
 24  F                              91498 non-null  int8
 25  M                              91498 non-null  int64
 26  RFM                            91498 non-null  int64
dtypes: float64(4), int16(2), int64(10), int8(1), object(10)
memory usage: 17.9+ MB